import type { Metadata } from 'next';
import { Lato } from 'next/font/google';
import { Header } from '@/app/components/header';
import './globals.css';

const lato = Lato({
  subsets: [],
  weight: '400',
  display: 'swap',
  variable: '--font-lato',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
